CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  name VARCHAR(255) NOT NULL,
  login_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE usage_logs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  endpoint VARCHAR(255) NOT NULL,
  method VARCHAR(10) NOT NULL,
  user_id INT,
  timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id),
  status_code INT NOT NULL
);

CREATE TABLE usage_stats (
  id INT AUTO_INCREMENT PRIMARY KEY,
  session_id VARCHAR(255) NOT NULL,
  user_id INT,
  game_id VARCHAR(255),
  hand_id VARCHAR(255),
  action_type VARCHAR(255),
  game_state JSON,
  timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE blackjack_game_state (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  session_id VARCHAR(255) NOT NULL,
  shoe JSON NOT NULL,
  user_hand JSON NOT NULL,
  dealer_hand JSON NOT NULL,
  count INT NOT NULL DEFAULT 0,
  true_count FLOAT NOT NULL DEFAULT 0,
  user_balance INT NOT NULL DEFAULT 1000,
  double_bet BOOLEAN NOT NULL DEFAULT FALSE,
  minimum_bet INT NOT NULL DEFAULT 5,
  timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id)
);

